## Travis config file to build a package

language: r

cache: packages

r:
  - release
  - devel

before_install:
  - sudo apt-get update
  - sudo apt-get install libfftw3-dev libgsl-dev
  
script:
  # Test first the fitting results against pli code
  - R -e "update.packages(ask = FALSE)"
  - R -e "install.packages(c('testthat', 'roxygen2'))"
  - R -e "devtools::install_deps()"
  - R -e "TEST_PSDFIT <- TRUE; devtools::test(filter = 'psdfit')"
  - R -e "TEST_XMIN <- TRUE; devtools::test(filter = 'xmin')"
  # Then test the whole package
  - R CMD build .
  - travis_wait R CMD check *tar.gz --as-cran --run-dontrun --run-donttest
  
after_success:
  - Rscript -e 'covr::codecov()'
  
after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;
